kind: pipeline
type: docker
name: dev-build

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:alpine
  commands:
    - npm install

- name: test
  image: node:alpine
  commands:
    - npm run test

- name: dist
  image: node:alpine
  commands:
    - npm run docs
    - npm run dist

- name: publish
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: hostname
    username: 
      from_secret: username
    password: 
      from_secret: password
    port: 22
    target: /var/www/lambdas
    source: 
      - docs
      - dist
      - coverage