kind: pipeline
type: docker
name: lambdas

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:alpine
  commands:
    - npm install

- name: test
  image: node:alpine
  commands:
    - npm run test

- name: build
  image: node:alpine
  commands:
    - npm run docs
    - npm run build

- name: publish-doc
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: hostname
    username: 
      from_secret: username
    password: 
      from_secret: password
    port: 22
    rm: true
    strip_components: 1
    target: /var/www/lambdas
    source: docs

- name: publish-umd
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: hostname
    username: 
      from_secret: username
    password: 
      from_secret: password
    port: 22
    strip_components: 1
    target: /var/www/myumd/lambdas
    source: dist