kind: pipeline
type: docker
name: dev-build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: node:13.14.0-alpine3.10
  commands:
    - npm install
    - npm run test
    - npm run docs
    - npm run build